package is.interpreter.analizzatori;

public enum Simboli {
	COMANDO_INVALIDO, NEW, DEL,
	MV, MVOFF, SCALE, LS, ALL, 
	GROUPS, GRP, UNGRP, AREA, PUNTO,
	PERIMETER, CIRCLE, RECTANGLE, 
	IMG, TONDA_APERTA, TONDA_CHIUSA,
	VIRGOLA, EOF, UNDO, REDO
}//Simboli
